### ISSUE TITLE
 java.lang.NoSuchMethodException: org.eclipse.emt4j.agent.common.rule.AgentReferenceClassRule.set(java.lang.String)

### ISSUE THREAD

**Issue by qiuchenjian** [adoptium/emt4j#49] opened 2024-03-11 08:15 UTC
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.emt4j.agent.jdk8.MainAgent.premain(MainAgent.java:82)
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.emt4j.agent.jdk8.MainAgent.premain(MainAgent.java:61)
	... 6 more
Caused by: java.lang.RuntimeException: org.eclipse.emt4j.common.JdkMigrationException: InstanceRuleManager init exception!
	at org.eclipse.emt4j.agent.common.AgentInit.init(AgentInit.java:30)
	... 11 more
Caused by: org.eclipse.emt4j.common.JdkMigrationException: InstanceRuleManager init exception!
	at org.eclipse.emt4j.common.rule.InstanceRuleManager.init(InstanceRuleManager.java:88)
	at org.eclipse.emt4j.agent.common.AgentFacade.initInstanceRules(AgentFacade.java:94)
	at org.eclipse.emt4j.agent.common.AgentFacade.init(AgentFacade.java:72)
	at org.eclipse.emt4j.agent.common.AgentInit.init(AgentInit.java:27)
	... 11 more
Caused by: java.lang.NoSuchMethodException: org.eclipse.emt4j.agent.common.rule.AgentReferenceClassRule.set(java.lang.String)
	at java.lang.Class.getMethod(Class.java:1786)
	at org.eclipse.emt4j.common.rule.InstanceRuleManager.setValue(InstanceRuleManager.java:93)
	at org.eclipse.emt4j.common.rule.InstanceRuleManager.init(InstanceRuleManager.java:78)
	... 14 more
```

When I usse
```
            <plugin>
                <groupId>org.eclipse.emt4j</groupId>
                <artifactId>emt4j-maven-plugin</artifactId>
                <version>0.8.0</version>
                <executions>
                    <execution>
                        <phase>initialize</phase>
                        <goals>
                            <goal>inject-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>check</id>
                        <phase>test</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <fromVersion>8</fromVersion>
                    <toVersion>17</toVersion>
                    <outputFile>report_running.html</outputFile>
                </configuration>
            </plugin>
```

**Comment by D-D-H** [comment] 2024-03-13 17:20
Does this problem happen if 'toVersion' is 11?

**Comment by D-D-H** [comment] 2024-03-14 03:12
Hi, @qiuchenjian 

I cannot reproduce the problem in my local simple projects.

Have you tried it in other java projects?

**Comment by qiuchenjian** [comment] 2024-03-14 03:27
hi D-D-H

`public void startElement(String uri, String localName, String qName, Attributes attributes) throws SAXException {
            currentValue.setLength(0);
            if (qName.equals("rule")) {
                confRuleItem = new ConfRuleItem();
                confRuleItem.setDesc(attributes.getValue("desc"));
                confRuleItem.setType(attributes.getValue("type"));
                confRuleItem.setResultCode(attributes.getValue("result-code"));
                confRuleItem.setSubResultCode(attributes.getValue("sub-result-code"));
                confRuleItem.setPriority(attributes.getValue("priority"));
                List<String[]> userDefineAttrs = new ArrayList<>(attributes.getLength());
                for (int i = 0; i < attributes.getLength(); i++) {
                    String attrName = attributes.getLocalName(i);`

the attrName of getLocalName is empty，but the value is right，so I think rule.xml has been read，but i dont know how getLocalName get

**Comment by D-D-H** [comment] 2024-03-14 03:50
What's the version of JDK that you are using to run the command?

**Comment by qiuchenjian** [comment] 2024-03-18 08:06
> What's the version of JDK that you are using to run the command?

USE JDK 8

**Comment by qiuchenjian** [comment] 2024-03-18 08:10
Hello ，
Will this project of emt4j be updated later?
If I update from jdk8 to jdk17， it seems use the rule of 8->11 and the rule of 11 -> 17 ,  I think this disign isn't precise
![image](https://github.com/adoptium/emt4j/assets/35337452/f1be35bf-298f-445c-98d4-05d3ba8aea52)

**Comment by qiuchenjian** [comment] 2024-03-18 08:45
Hello ，
Will this project of emt4j be updated later?

**Comment by D-D-H** [comment] 2024-03-18 08:55
> If I update from jdk8 to jdk17， it seems use the rule of 8->11 and the rule of 11 -> 17 , I think this disign isn't precise

Yes, it combines the rules of 8->11 and 11 -> 17. 

>  I think this disign isn't precise

Could you add more detailed comments?

**Comment by D-D-H** [comment] 2024-03-18 08:56
> Hello ， Will this project of emt4j be updated later?

Yes. We created a new PR for auto-fix last week. And after it is merged, we will release a new version.

**Comment by D-D-H** [comment] 2024-03-18 09:01
We have an internal version of EMT4J.

Currently, most features are first developed internally. Then we will open-source the features that are general and stable enough.

**Comment by qiuchenjian** [comment] 2024-03-18 09:13
Get it, thank you for replay.  

> We have an internal version of EMT4J.
> 
> Currently, most features are first developed internally. Then we will open-source the features that are general and stable enough.

**Comment by D-D-H** [comment] 2024-03-18 09:20
> can I modify it like this ？？？

Not sure. We'd better know the root cause first.

**Comment by D-D-H** [comment] 2024-03-18 09:21
Have you tried emt4j on an empty project?

**Comment by qiuchenjian** [comment] 2024-03-18 10:28
> > can I modify it like this ？？？
> 
> Not sure. We'd better know the root cause first.

empty project is also wrong .   I think the qname is right in any situation of rule.xml， but localName is restricted sometimes。

so why we use localName here ？

```
    public String getLocalName(int index) {
        if (!fNamespaces) {
            return "";
        }
        if (index < 0 || index >= fLength) {
            return null;
        }
        return fAttributes[index].name.localpart;
    } 

    public String getQName(int index) {
        if (index < 0 || index >= fLength) {
            return null;
        }
        String rawname = fAttributes[index].name.rawname;
        return rawname != null ? rawname : "";
    } 
```

**Comment by D-D-H** [comment] 2024-03-18 11:37
@qiuchenjian 

I'll take a deep look at it and back to you soon.

**Comment by qiuchenjian** [comment] 2024-03-19 01:15
I have solved this problem a few days ago and provided a way to change it to qname

**Comment by D-D-H** [comment] 2024-03-19 03:19
From the information you provided, I think you can try to use the `Remote Debug` function to debug what really happens.

1. run mvn cmd in terminal or another window of Idea, like:
   ```
   $ MAVEN_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5001" mvn clean test
   ```
3. set up Idea remote debug configuration and launch it


![image](https://github.com/adoptium/emt4j/assets/33491035/1adf051d-40f1-49f2-bceb-44aa1923f84e)


> I have solved this problem a few days ago and provided a way to change it to qname

I agree that we should fix this problem in Emt4j. I just want to confirm the root cause fisrt.

**Comment by qiuchenjian** [comment] 2024-03-19 06:44
1. First,  add some logs in startElement method and  install the emt4j project 
2. In my project, add the maven_opts like that, then run mvn  test, now the project is :
![image](https://github.com/adoptium/emt4j/assets/35337452/f10eeccd-031b-4593-9c9c-f274128c32e2)
3. In emt4j project , set up remote debug and add some breaks , like this
![image](https://github.com/adoptium/emt4j/assets/35337452/53c7d2f1-f589-484a-8052-1233c6024181)
4. My project continue run mvn test, and print the log
![image](https://github.com/adoptium/emt4j/assets/35337452/e273128d-074c-4163-a52f-6125e991b102)
5. But emt4j didn't stop the break

**Comment by qiuchenjian** [comment] 2024-03-19 06:52
![image](https://github.com/adoptium/emt4j/assets/35337452/68fca8a1-10db-41a4-a578-8dac58a24242)

**Comment by D-D-H** [comment] 2024-03-19 08:13
@qiuchenjian 

Please try to remove your local maven cache of emt4j and checkout the project to `v0.8.0` without any changes.. Then retry.

**Comment by D-D-H** [comment] 2024-03-19 11:28
@qiuchenjian 
Thanks for the confirmation.
I think you are right. We should use `getQName` there.
Would you like to submit a PR to fix this problem?

**Comment by qiuchenjian** [comment] 2024-03-19 11:30
> @qiuchenjian Thanks for the confirmation. I think you are right. We should use `getQName` there. Would you like to submit a PR to fix this problem?

OK, i will submit it in a few days

**Closed** 2024-03-20 04:05 UTC
